import pg from 'pg';
const { Client } = pg;

const connectionString = "postgresql://postgres:l2k4csJdAHFDDmgK@db.luzfqnhhikbvilaivhyj.supabase.co:5432/postgres";

const client = new Client({ connectionString });

async function setupDB() {
  await client.connect();
  console.log('Connected to DB');

  try {
    await client.query(`
      CREATE TABLE IF NOT EXISTS journal (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        date TIMESTAMPTZ,
        situasi TEXT,
        pikiran TEXT,
        emotions JSONB,
        "buktiD" TEXT,
        "buktiE" TEXT,
        alternatif TEXT,
        tindakan TEXT,
        tag TEXT,
        user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL
      );

      CREATE TABLE IF NOT EXISTS principles (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        text TEXT,
        source TEXT,
        status TEXT,
        notes TEXT,
        user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL
      );

      CREATE TABLE IF NOT EXISTS concepts (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        name TEXT,
        "desc" TEXT,
        problem TEXT,
        source TEXT,
        discipline TEXT,
        user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL
      );

      CREATE TABLE IF NOT EXISTS spiral (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        date TIMESTAMPTZ,
        insight TEXT,
        delta TEXT,
        user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL
      );
    `);
    console.log('Tables created successfully.');

    const tables = ['journal', 'principles', 'concepts', 'spiral'];
    for (const table of tables) {
      await client.query(`ALTER TABLE ${table} ENABLE ROW LEVEL SECURITY;`);
      
      await client.query(`
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_policies WHERE tablename = '${table}' AND policyname = 'Users can manage their own data'
            ) THEN
                CREATE POLICY "Users can manage their own data" ON ${table}
                FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
            END IF;
        END
        $$;
      `);
      console.log(`RLS enabled for ${table}`);
    }

  } catch (err) {
    console.error('Error setting up DB:', err);
  } finally {
    await client.end();
  }
}

setupDB();
