-- Create Journal Table
CREATE TABLE IF NOT EXISTS journal (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  date TIMESTAMPTZ,
  situasi TEXT,
  pikiran TEXT,
  emotions JSONB,
  "buktiD" TEXT,
  "buktiE" TEXT,
  alternatif TEXT,
  tindakan TEXT,
  tag TEXT,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL
);

-- Create Principles Table
CREATE TABLE IF NOT EXISTS principles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  text TEXT,
  source TEXT,
  status TEXT,
  notes TEXT,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL
);

-- Create Concepts Table
CREATE TABLE IF NOT EXISTS concepts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT,
  "desc" TEXT,
  problem TEXT,
  source TEXT,
  discipline TEXT,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL
);

-- Create Spiral Table
CREATE TABLE IF NOT EXISTS spiral (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  date TIMESTAMPTZ,
  insight TEXT,
  delta TEXT,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL
);

-- Enable RLS
ALTER TABLE journal ENABLE ROW LEVEL SECURITY;
ALTER TABLE principles ENABLE ROW LEVEL SECURITY;
ALTER TABLE concepts ENABLE ROW LEVEL SECURITY;
ALTER TABLE spiral ENABLE ROW LEVEL SECURITY;

-- Create Policies
CREATE POLICY "Users can manage their own journal entries" ON journal FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can manage their own principles" ON principles FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can manage their own concepts" ON concepts FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can manage their own spiral entries" ON spiral FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Create Action Queue Table (Zeigarnik Hook)
CREATE TABLE IF NOT EXISTS action_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  question TEXT NOT NULL,
  is_tested BOOLEAN DEFAULT FALSE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL
);

ALTER TABLE action_queue ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own action queue" ON action_queue FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
